"""Base strategy interface and signal dataclass.

All strategy implementations inherit from Strategy and produce Signal objects
that the executor uses to place trades.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import date
from enum import Enum

import pandas as pd

from ait.data.options_chain import OptionsChain, OptionContract


class SignalDirection(str, Enum):
    BULLISH = "bullish"
    BEARISH = "bearish"
    NEUTRAL = "neutral"  # For income strategies (iron condor, strangle)


@dataclass
class Signal:
    """A trade signal generated by a strategy."""

    symbol: str
    strategy_name: str
    direction: SignalDirection
    confidence: float  # 0.0 to 1.0

    # Primary leg
    contract: OptionContract | None = None
    action: str = "BUY"  # BUY or SELL
    quantity: int = 1

    # For multi-leg strategies (spreads, condors)
    legs: list[dict] = field(default_factory=list)
    # Each leg: {"contract": OptionContract, "action": "BUY"/"SELL", "ratio": 1}

    # Risk parameters
    entry_price: float = 0.0  # Expected fill price (mid for limit orders)
    max_loss: float = 0.0  # Maximum possible loss
    max_profit: float = 0.0  # Maximum possible profit
    stop_loss: float | None = None
    take_profit: float | None = None

    # Context
    iv_rank: float = 0.0  # IV percentile (0-100)
    underlying_price: float = 0.0
    expiry: date | None = None

    @property
    def risk_reward(self) -> float:
        """Risk/reward ratio. Higher is better."""
        if self.max_loss <= 0:
            return 0.0
        return self.max_profit / self.max_loss

    @property
    def is_defined_risk(self) -> bool:
        """Whether this trade has defined (capped) maximum loss."""
        return self.max_loss > 0

    def __repr__(self) -> str:
        return (
            f"Signal({self.symbol} {self.strategy_name} {self.direction.value} "
            f"conf={self.confidence:.2f} entry={self.entry_price:.2f})"
        )


class Strategy(ABC):
    """Abstract base class for all trading strategies."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Strategy name identifier."""
        ...

    @property
    @abstractmethod
    def direction_bias(self) -> SignalDirection | None:
        """Inherent directional bias. None for direction-neutral strategies."""
        ...

    @abstractmethod
    def generate_signals(
        self,
        symbol: str,
        chain: OptionsChain,
        market_direction: SignalDirection,
        confidence: float,
        iv_rank: float,
        historical_data: pd.DataFrame | None = None,
    ) -> list[Signal]:
        """Generate trade signals for a symbol.

        Args:
            symbol: Ticker symbol
            chain: Filtered options chain
            market_direction: ML-predicted market direction
            confidence: ML model confidence
            iv_rank: Current IV percentile (0-100)
            historical_data: Recent price history for context

        Returns:
            List of signals (may be empty if no good opportunities)
        """
        ...

    def _find_strike_by_delta(
        self,
        contracts: list[OptionContract],
        target_delta: float,
    ) -> OptionContract | None:
        """Find the contract closest to a target delta."""
        if not contracts:
            return None
        return min(contracts, key=lambda c: abs(abs(c.delta) - target_delta))

    def _find_strike_near(
        self,
        contracts: list[OptionContract],
        target_strike: float,
    ) -> OptionContract | None:
        """Find the contract closest to a target strike price."""
        if not contracts:
            return None
        return min(contracts, key=lambda c: abs(c.strike - target_strike))

    def _filter_liquid(self, contracts: list[OptionContract]) -> list[OptionContract]:
        """Filter to only liquid contracts."""
        return [c for c in contracts if c.is_liquid]
